// Все видимые игроку строки. Смена языка = замена этого модуля.
export const STR = {
  title: 'ПОСЛЕДНЯЯ СВЕЧА',
  subtitle: 'тёмная ARPG',
  tapToStart: 'Коснись, чтобы начать',
  newGame: 'Новая игра',
  continueGame: 'Продолжить',
  chooseClass: 'Выбери героя',
  del: 'Стереть',
  confirmDelete: 'Стереть сохранение безвозвратно?',
  yes: 'Да', no: 'Нет', back: 'Назад', close: 'Закрыть',

  classes: {
    barbarian: { name: 'Варвар', desc: 'Ярость и сталь. Рубит толпы в упор, чем дольше бой — тем страшнее его гнев.' },
    huntress: { name: 'Охотница', desc: 'Стреляй и исчезай. Лук, ловушки и яд — смерть приходит издалека.' },
    mage: { name: 'Маг', desc: 'Стеклянная буря. Огонь, лёд и молния испепеляют всё — если успеет.' },
    warlock: { name: 'Чернокнижник', desc: 'Жнец душ. Проклятия гноят врагов, а мёртвые встают служить ему.' },
    druid: { name: 'Друид', desc: 'Зверь внутри. Волк, медведь и гнев самой природы.' },
  },
  resources: { fury: 'Ярость', focus: 'Концентрация', mana: 'Мана', souls: 'Души', wrath: 'Гнев' },
  stats: { str: 'Сила', dex: 'Ловкость', int: 'Интеллект', vit: 'Живучесть' },
  statPoints: 'Очки характеристик', talentPoints: 'Очки талантов',
  level: 'Уровень', exp: 'Опыт', gold: 'Золото',
  dmg: 'Урон', armor: 'Броня', crit: 'Крит', aspd: 'Скор. атаки',
  resFire: 'Сопр. огню', resCold: 'Сопр. холоду', resLight: 'Сопр. молнии', resPoison: 'Сопр. яду',

  town: 'Лагерь у Последней Свечи',
  vendor: 'Скупщик', stash: 'Сундук', altar: 'Алтарь талантов', portalTo: 'Врата',
  buy: 'Купить', sell: 'Продать', gamble: 'Гэмбл (кот в мешке)',
  respec: 'Сброс талантов', respecCost: 'Цена сброса',
  notEnoughGold: 'Не хватает золота',
  inventoryFull: 'Инвентарь полон',
  stashFull: 'Сундук полон',

  inventory: 'Инвентарь', character: 'Герой', talents: 'Таланты', equipped: 'Надето',
  equip: 'Надеть', unequip: 'Снять', drop: 'Выбросить', use: 'Использовать', toStash: 'В сундук', fromStash: 'Забрать',
  requires: 'Требуется', levelShort: 'ур.',
  learn: 'Изучить', maxRank: 'МАКС', rank: 'Ранг', assign: 'На кнопку',

  rarity: { common: 'Обычный', magic: 'Магический', rare: 'Редкий', unique: 'Уникальный', set: 'Сетовый' },
  slots: { weapon: 'Оружие', offhand: 'Левая рука', helm: 'Шлем', chest: 'Доспех', gloves: 'Перчатки', belt: 'Пояс', boots: 'Сапоги', amulet: 'Амулет', ring1: 'Кольцо', ring2: 'Кольцо' },

  potions: 'Зелья', potionFull: 'Здоровье полно', noPotions: 'Зелий нет',
  killed: 'убит', youDied: 'ТЫ ПОГИБ',
  deathHint: 'Свеча догорела... но фитиль ещё тлеет. Золото потеряно: ',
  revive: 'Восстать в лагере',
  levelUp: 'НОВЫЙ УРОВЕНЬ!',
  eliteAffix: { fast: 'Стремительный', fire: 'Огненный', cold: 'Ледяной', vampiric: 'Вампирический', storm: 'Грозовой' },
  bossWarning: '⚠ Логово босса',
  actCleared: 'Акт пройден!',
  gameCleared: 'Владыка Бездны повержен. Свеча горит. Открыты бесконечные Порталы и сложность КОШМАР.',
  rift: 'Портал', riftLevel: 'Портал ур.',
  difficulty: { normal: 'Обычный', nightmare: 'Кошмар', hell: 'Ад' },
  acts: {
    1: { name: 'Проклятый погост', boss: 'Костяной Патриарх' },
    2: { name: 'Чумные катакомбы', boss: 'Мать Чумы' },
    3: { name: 'Пыточные залы', boss: 'Палач' },
    4: { name: 'Врата Ада', boss: 'Владыка Бездны' },
  },
  floor: 'Этаж', enter: 'Войти', touchHintMove: 'Левый палец — движение', touchHintSkills: 'Правый — атака и умения',
  settings: 'Настройки', sound: 'Звук', shake: 'Тряска экрана', textSize: 'Крупный текст', flash: 'Вспышки',
  saveNote: 'Игра сохраняется сама. Работает без интернета.',
  credits: 'Графика персонажей и монстров: проект Flare — Clint Bellanger, Justin Nichol и команда (CC-BY-SA 3.0). Спасибо за свободное искусство.',
  offlineReady: 'Игра скачана: можно играть без сети',
  mobNames: {
    skeleton: 'Скелет-воин', zombie: 'Гниющий труп', ghoul: 'Гуль', bloater: 'Раздутый труп',
    cultist: 'Чумной культист', hound: 'Адская гончая', imp: 'Бес', knight: 'Рыцарь Ада',
    boss_bone: 'Костяной Патриарх', boss_plague: 'Мать Чумы', boss_executioner: 'Палач', boss_abyss: 'Владыка Бездны',
    skeleton_minion: 'Восставший скелет', demon_minion: 'Прислужник-демон',
  },
};
